//Cracked by Roath
// /d/shenlong/unique_list.h

mapping unique_list = ([
        "太极十三势" : "/kungfu/class/wudang/force_book.c",
        "旧竹片" : "/d/shaolin/obj/book-bamboo.c",
        "薄绢" : "/d/shaolin/obj/book-silk.c",
        "紫霞秘笈" : "/d/huashan/obj/zixia_book.c",
        "棒法图解" : "/d/gaibang/obj/stick_book.c",
        "杖法图解" : "/d/huashan/obj/staff_book.c",
        "人参果" : "/d/wudang/obj/renshen_guo.c",
        "蓝玉钵" : "/d/xingxiu/obj/yaobo.c",
        "神木王鼎" : "/d/xingxiu/obj/muding.c",
        "降魔杵" : "/clone/weapon/xiangmo-chu.c",
        "倚天剑" : "/clone/weapon/yitian-jian.c",
        "玉箫" : "/clone/unique/yuxiao.c",
        "伏魔刀" : "/clone/unique/fumo-dao.c",
        "金蛇剑" : "/clone/unique/jinshe-jian.c",
        "鳄嘴剪" : "/clone/unique/eyujian.c",
        "鳄尾鞭" : "/clone/unique/eweibian.c",
        "金刚罩" : "/d/shaolin/obj/jingang-zhao.c",
        "软猬甲" : "/d/taohua/obj/ruanwei-jia.c",
        "玄铁重剑" : "/clone/unique/xuantie-jian.c",
        "金蛇锥" : "/d/huashan/obj/jinshe-zhui.c",
        "玉竹杖" : "/clone/unique/yuzhu-zhang.c",
        "乌蚕衣" : "/d/xueshan/obj/wucan-yi.c",
        "七绝针" : "/clone/weapon/qijue.c",
        "鱼肠剑" : "/clone/unique/yuchang-jian.c",

        "龙象般若经" : "/d/qilian/obj/lx-jing.c",
        "神照经" : "/d/city/npc/obj/shenzhao.c",
        "血刀" : "/clone/unique/xuedao.c",
        "鸳刀" : "/clone/unique/yuandao.c",
        "鸯刀" : "/clone/unique/yangdao.c",
]);
