//Cracked by Roath
// /d/huanghe/bangjob/bangjob50000.c

// inherit SKILL;

inherit F_CLEAN_UP;

mapping *bangjobs = ({
        ([      "name"  :  "李沅芷",
                "file"  :  "/d/city/npc/yuanzhi",
                "area"  :  "扬州城提督府",
                "type"  :  "杀",
                "bonus" :  100,
                "score" :  50,
        ]),

        ([      "name"  :  "凌退思",
                "file"  :  "/d/city/npc/tuisi",
                "area"  :  "扬州翰林府",
                "type"  :  "杀",
                "bonus" :  50,
                "score" :  20,
        ]),

        ([      "name"  :  "林震南",
                "file"  :  "/d/city/npc/linzhennan",
                "area"  :  "扬州福威镖局",
                "type"  :  "杀",
                "bonus" :  60,
                "score" :  25,
        ]),

        ([      "name"  :  "李克秀",
                "file"  :  "/d/city/npc/kexiu",
                "area"  :  "扬州城提督府",
                "type"  :  "杀",
                "bonus" :  120,
                "score" :  60,
        ]),

        ([      "name"  :  "忽伦大虎",
                "file"  :  "/d/changbai/npc/juren1",
                "area"  :  "辽东",
                "type"  :  "杀",
                "bonus" :  60,
                "score" :  15,
        ]),

        ([      "name"  :  "忽伦二虎",
                "file"  :  "/d/changbai/npc/juren2",
                "area"  :  "辽东",
                "type"  :  "杀",
                "bonus" :  55,
                "score" :  14,
        ]),

        ([      "name"  :  "忽伦三虎",
                "file"  :  "/d/changbai/npc/juren3",
                "area"  :  "辽东",
                "type"  :  "杀",
                "bonus" :  50,
                "score" :  13,
        ]),

        ([      "name"  :  "忽伦四虎",
                "file"  :  "/d/changbai/npc/juren4",
                "area"  :  "辽东",
                "type"  :  "杀",
                "bonus" :  45,
                "score" :  12,
        ]),

        ([      "name"  :  "袁冠男",
                "file"  :  "/d/forest/npc/guannan",
                "area"  :  "扬州郊外",
                "type"  :  "杀",
                "bonus" :  80,
                "score" :  25,
        ]),

        ([      "name"  :  "林玉龙",
                "file"  :  "/d/forest/npc/lin",
                "area"  :  "扬州郊外",
                "type"  :  "杀",
                "bonus" :  80,
                "score" :  25,
        ]),

        ([      "name"  :  "任飞燕",
                "file"  :  "/d/forest/npc/ren",
                "area"  :  "扬州郊外",
                "type"  :  "杀",
                "bonus" :  80,
                "score" :  25,
        ]),

        ([      "name"  :  "祖千秋",
                "file"  :  "/d/forest/npc/qiu",
                "area"  :  "黄河岸边",
                "type"  :  "杀",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "萧中慧",
                "file"  :  "/d/forest/npc/zhonghui",
                "area"  :  "扬州郊外",
                "type"  :  "杀",
                "bonus" :  80,
                "score" :  25,
        ]),

        ([      "name"  :  "海老公",
                "file"  :  "/d/jiaxing/npc/hai",
                "area"  :  "嘉兴城",
                "type"  :  "杀",
                "bonus" :  40,
                "score" :  12,
        ]),

        ([      "name"  :  "向问天",
                "file"  :  "/d/jiaxing/npc/xiang",
                "area"  :  "扬州郊外",
                "type"  :  "杀",
                "bonus" :  120,
                "score" :  40,
        ]),

        ([      "name"  :  "陈浒",
                "file"  :  "/d/quanzhou/npc/chenhu",
                "area"  :  "泉州扬威武馆",
                "type"  :  "杀",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "贾人达",
                "file"  :  "/d/quanzhou/npc/jiarenda",
                "area"  :  "泉州山路",
                "type"  :  "杀",
                "bonus" :  60,
                "score" :  20,
        ]),

        ([      "name"  :  "马五德",
                "file"  :  "/d/quanzhou/npc/mawude",
                "area"  :  "泉州扬威武馆",
                "type"  :  "杀",
                "bonus" :  80,
                "score" :  30,
        ]),

        ([      "name"  :  "江百胜",
                "file"  :  "/d/taishan/npc/jiang",
                "area"  :  "泰山",
                "type"  :  "杀",
                "bonus" :  80,
                "score" :  20,
        ]),

        ([      "name"  :  "铁八卦",
                "file"  :  "/d/city/obj/tiebagua",
                "type"  :  "寻",
                "bonus" :  20,
                "score" :  5,
        ]),

        ([      "name"  :  "铁甲",
                "file"  :  "/clone/armor/tiejia",
                "type"  :  "寻",
                "bonus" :  12,
                "score" :  3,
        ]),

        ([      "name"  :  "雪莲",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  80,
                "score" :  20,
        ]),

        ([      "name"  :  "百草丹",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "雄黄丸",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "狐狸皮",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "长白山人参",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  100,
                "score" :  30,
        ]),

        ([      "name"  :  "当归",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "大血藤",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  60,
                "score" :  15,
        ]),

        ([      "name"  :  "人参果",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  120,
                "score" :  40,
        ]),

        ([      "name"  :  "续命八丹",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  120,
                "score" :  40,
        ]),

        ([      "name"  :  "首乌精",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "田七鲨胆散",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "无常丹",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "灵芝",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  80,
                "score" :  20,
        ]),

        ([      "name"  :  "何首乌",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  60,
                "score" :  15,
        ]),

        ([      "name"  :  "老山参",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "铁球",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  80,
                "score" :  20,
        ]),

        ([      "name"  :  "武士刀",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  20,
                "score" :  5,
        ]),

        ([      "name"  :  "武士服",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  20,
                "score" :  5,
        ]),

        ([      "name"  :  "陈圆圆手帕",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "施将军令牌",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  50,
                "score" :  12,
        ]),

        ([      "name"  :  "骰子",
                "file"  :  "  ",
                "type"  :  "寻",
                "bonus" :  60,
                "score" :  15,
        ]),

        ([      "name"  :  "黄衣军服",
                "file"  :  "/d/dali/obj/ycloth",
                "type"  :  "寻",
                "bonus" :  20,
                "score" :  5,
        ]),

        ([      "name"  :  "贝壳项链",
                "file"  :  "/d/dali/npc/obj/shelllace",
                "type"  :  "寻",
                "bonus" :  80,
                "score" :  30,
        ]),

        ([      "name"  :  "蛮刀",
                "file"  :  "/d/dali/obj/mandao",
                "type"  :  "寻",
                "bonus" :  60,
                "score" :  15,
        ]),

        ([      "name"  :  "锦衣军服",
                "file"  :  "/d/dali/obj/jcloth",
                "type"  :  "寻",
                "bonus" :  60,
                "score" :  25,
        ]),

        ([      "name"  :  "金钗",
                "file"  :  "/d/forest/npc/obj/jinchai",
                "type"  :  "寻",
                "bonus" :  60,
                "score" :  25,
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),

        ([      "type"  :  "截镖",
        ]),
});

void create() { seteuid(getuid()); }

mapping query_job()
{
        return bangjobs[random(sizeof(bangjobs))];
}

